#!/bin/bash
# Authors:
#
# Matthieu Petiteau <mpetiteau.pro@gmail.com>
# Grant Handy <grantshandy@gmail.com>
#
# Date: 26.09.2019
#
# This script fetches the tube line statuses from the TFL API https://api.tfl.gov.uk and returns the results in the terminal.



if [[ $2 == "" ]]; then
	echo "Please type the name of the line you would like to view."
else
	COMPLEX=$(alltubes | grep -i $1)
fi

SIMPLE=$(echo "$COMPLEX" | sed 's/\●//g')

if [[ $1 == "complex" ]]; then
	echo $COMPLEX
fi

if [[ $1 == "simple" ]]; then
	echo $SIMPLE
fi
